//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SATSR
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESSAGE_DETAIL
    {
        public int ID { get; set; }
        public int ID_MESSAGE { get; set; }
        public int ID_USER_TO { get; set; }
        public bool DELIVERED { get; set; }
        public Nullable<bool> EMAIL_NOTIFICATION { get; set; }
    
        public virtual MESSAGE MESSAGE { get; set; }
        public virtual USER USER { get; set; }
    }
}
