//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SATSR
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESSAGE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MESSAGE()
        {
            this.MESSAGE_DETAIL = new HashSet<MESSAGE_DETAIL>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ID_USER_FROM { get; set; }
        public int ID_STATUS { get; set; }
        public System.DateTime INSERT_DATE { get; set; }
        public string TITLE { get; set; }
        public string MESSAGE1 { get; set; }
        public string ICON { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MESSAGE_DETAIL> MESSAGE_DETAIL { get; set; }
        public virtual STATUS STATUS { get; set; }
        public virtual USER USER { get; set; }
    }
}
