//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SATSR
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class YEI3_SATEntities : DbContext
    {
        public YEI3_SATEntities()
            : base("name=YEI3_SATEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CONFIGURATION> CONFIGURATION { get; set; }
        public virtual DbSet<MENU> MENU { get; set; }
        public virtual DbSet<MESSAGE> MESSAGE { get; set; }
        public virtual DbSet<MESSAGE_DETAIL> MESSAGE_DETAIL { get; set; }
        public virtual DbSet<ROL> ROL { get; set; }
        public virtual DbSet<ROL_MENU> ROL_MENU { get; set; }
        public virtual DbSet<SOURCE_TYPE> SOURCE_TYPE { get; set; }
        public virtual DbSet<STATUS> STATUS { get; set; }
        public virtual DbSet<UPDATE> UPDATE { get; set; }
        public virtual DbSet<USER> USER { get; set; }
        public virtual DbSet<USER_ROL> USER_ROL { get; set; }
        public virtual DbSet<USER_SEARCH_HISTORY> USER_SEARCH_HISTORY { get; set; }
        public virtual DbSet<C69> C69 { get; set; }
        public virtual DbSet<C69_B> C69_B { get; set; }
        public virtual DbSet<T69> T69 { get; set; }
    
        public virtual int SEARCH_RFC_69(string rFC)
        {
            var rFCParameter = rFC != null ?
                new ObjectParameter("RFC", rFC) :
                new ObjectParameter("RFC", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SEARCH_RFC_69", rFCParameter);
        }
    
        public virtual int SEARCH_RFC_69B(string rFC)
        {
            var rFCParameter = rFC != null ?
                new ObjectParameter("RFC", rFC) :
                new ObjectParameter("RFC", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SEARCH_RFC_69B", rFCParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SEARCH_69(string rFC)
        {
            var rFCParameter = rFC != null ?
                new ObjectParameter("RFC", rFC) :
                new ObjectParameter("RFC", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SEARCH_69", rFCParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SIMPLE_SEARCH_69(string rFC)
        {
            var rFCParameter = rFC != null ?
                new ObjectParameter("RFC", rFC) :
                new ObjectParameter("RFC", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SIMPLE_SEARCH_69", rFCParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SIMPLE_SEARCH_69b(string rFC)
        {
            var rFCParameter = rFC != null ?
                new ObjectParameter("RFC", rFC) :
                new ObjectParameter("RFC", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SIMPLE_SEARCH_69b", rFCParameter);
        }
    
        public virtual ObjectResult<SIMPLE_SEARCH_RFC_69_Result> SIMPLE_SEARCH_RFC_69(string rFC)
        {
            var rFCParameter = rFC != null ?
                new ObjectParameter("RFC", rFC) :
                new ObjectParameter("RFC", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SIMPLE_SEARCH_RFC_69_Result>("SIMPLE_SEARCH_RFC_69", rFCParameter);
        }
    
        public virtual ObjectResult<SIMPLE_SEARCH_RFC_69B_Result> SIMPLE_SEARCH_RFC_69B(string rFC)
        {
            var rFCParameter = rFC != null ?
                new ObjectParameter("RFC", rFC) :
                new ObjectParameter("RFC", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SIMPLE_SEARCH_RFC_69B_Result>("SIMPLE_SEARCH_RFC_69B", rFCParameter);
        }
    
        public virtual ObjectResult<SEARCH_DETAIL_69_Result> SEARCH_DETAIL_69(string tABLA, string rFC)
        {
            var tABLAParameter = tABLA != null ?
                new ObjectParameter("TABLA", tABLA) :
                new ObjectParameter("TABLA", typeof(string));
    
            var rFCParameter = rFC != null ?
                new ObjectParameter("RFC", rFC) :
                new ObjectParameter("RFC", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SEARCH_DETAIL_69_Result>("SEARCH_DETAIL_69", tABLAParameter, rFCParameter);
        }
    
        public virtual ObjectResult<SEARCH_DETAIL_69B_Result> SEARCH_DETAIL_69B(string tABLA, string rFC)
        {
            var tABLAParameter = tABLA != null ?
                new ObjectParameter("TABLA", tABLA) :
                new ObjectParameter("TABLA", typeof(string));
    
            var rFCParameter = rFC != null ?
                new ObjectParameter("RFC", rFC) :
                new ObjectParameter("RFC", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SEARCH_DETAIL_69B_Result>("SEARCH_DETAIL_69B", tABLAParameter, rFCParameter);
        }
    
        public virtual ObjectResult<SIMPLE_SEARCH_RFC_69_BY_DATE_Result> SIMPLE_SEARCH_RFC_69_BY_DATE(string rFC, Nullable<int> tIPO, string fECHA)
        {
            var rFCParameter = rFC != null ?
                new ObjectParameter("RFC", rFC) :
                new ObjectParameter("RFC", typeof(string));
    
            var tIPOParameter = tIPO.HasValue ?
                new ObjectParameter("TIPO", tIPO) :
                new ObjectParameter("TIPO", typeof(int));
    
            var fECHAParameter = fECHA != null ?
                new ObjectParameter("FECHA", fECHA) :
                new ObjectParameter("FECHA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SIMPLE_SEARCH_RFC_69_BY_DATE_Result>("SIMPLE_SEARCH_RFC_69_BY_DATE", rFCParameter, tIPOParameter, fECHAParameter);
        }
    
        public virtual ObjectResult<SIMPLE_SEARCH_RFC_69B_BY_DATE_Result> SIMPLE_SEARCH_RFC_69B_BY_DATE(string rFC, Nullable<int> tIPO, string fECHA)
        {
            var rFCParameter = rFC != null ?
                new ObjectParameter("RFC", rFC) :
                new ObjectParameter("RFC", typeof(string));
    
            var tIPOParameter = tIPO.HasValue ?
                new ObjectParameter("TIPO", tIPO) :
                new ObjectParameter("TIPO", typeof(int));
    
            var fECHAParameter = fECHA != null ?
                new ObjectParameter("FECHA", fECHA) :
                new ObjectParameter("FECHA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SIMPLE_SEARCH_RFC_69B_BY_DATE_Result>("SIMPLE_SEARCH_RFC_69B_BY_DATE", rFCParameter, tIPOParameter, fECHAParameter);
        }
    
        public virtual ObjectResult<SEARCH_HISTORY_PERIOD_Result> SEARCH_HISTORY_PERIOD(Nullable<int> iD_USR, Nullable<System.DateTime> iNIT_PER, Nullable<System.DateTime> eND_PER)
        {
            var iD_USRParameter = iD_USR.HasValue ?
                new ObjectParameter("ID_USR", iD_USR) :
                new ObjectParameter("ID_USR", typeof(int));
    
            var iNIT_PERParameter = iNIT_PER.HasValue ?
                new ObjectParameter("INIT_PER", iNIT_PER) :
                new ObjectParameter("INIT_PER", typeof(System.DateTime));
    
            var eND_PERParameter = eND_PER.HasValue ?
                new ObjectParameter("END_PER", eND_PER) :
                new ObjectParameter("END_PER", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SEARCH_HISTORY_PERIOD_Result>("SEARCH_HISTORY_PERIOD", iD_USRParameter, iNIT_PERParameter, eND_PERParameter);
        }
    
        public virtual ObjectResult<GET_DETAIL_69_Result> GET_DETAIL_69(Nullable<int> iD_USR)
        {
            var iD_USRParameter = iD_USR.HasValue ?
                new ObjectParameter("ID_USR", iD_USR) :
                new ObjectParameter("ID_USR", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_DETAIL_69_Result>("GET_DETAIL_69", iD_USRParameter);
        }
    
        public virtual ObjectResult<GET_DETAIL_69B_Result> GET_DETAIL_69B(Nullable<int> iD_USR)
        {
            var iD_USRParameter = iD_USR.HasValue ?
                new ObjectParameter("ID_USR", iD_USR) :
                new ObjectParameter("ID_USR", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_DETAIL_69B_Result>("GET_DETAIL_69B", iD_USRParameter);
        }
    
        public virtual int DELIVERY_AUTOMATIC_SEARCH()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DELIVERY_AUTOMATIC_SEARCH");
        }
    
        public virtual ObjectResult<SIMPLE_SEARCH_RFC_69B_DATE_BY_DATE_Result> SIMPLE_SEARCH_RFC_69B_DATE_BY_DATE(string rFC, Nullable<int> tIPO, string fECHA)
        {
            var rFCParameter = rFC != null ?
                new ObjectParameter("RFC", rFC) :
                new ObjectParameter("RFC", typeof(string));
    
            var tIPOParameter = tIPO.HasValue ?
                new ObjectParameter("TIPO", tIPO) :
                new ObjectParameter("TIPO", typeof(int));
    
            var fECHAParameter = fECHA != null ?
                new ObjectParameter("FECHA", fECHA) :
                new ObjectParameter("FECHA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SIMPLE_SEARCH_RFC_69B_DATE_BY_DATE_Result>("SIMPLE_SEARCH_RFC_69B_DATE_BY_DATE", rFCParameter, tIPOParameter, fECHAParameter);
        }
    
        public virtual ObjectResult<SIMPLE_SEARCH_RFC_69B_DAY_BY_DATE_Result> SIMPLE_SEARCH_RFC_69B_DAY_BY_DATE(string rFC, Nullable<int> tIPO, string fECHA)
        {
            var rFCParameter = rFC != null ?
                new ObjectParameter("RFC", rFC) :
                new ObjectParameter("RFC", typeof(string));
    
            var tIPOParameter = tIPO.HasValue ?
                new ObjectParameter("TIPO", tIPO) :
                new ObjectParameter("TIPO", typeof(int));
    
            var fECHAParameter = fECHA != null ?
                new ObjectParameter("FECHA", fECHA) :
                new ObjectParameter("FECHA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SIMPLE_SEARCH_RFC_69B_DAY_BY_DATE_Result>("SIMPLE_SEARCH_RFC_69B_DAY_BY_DATE", rFCParameter, tIPOParameter, fECHAParameter);
        }
    
        public virtual ObjectResult<SIMPLE_SEARCH_RFC_69B_DAYDATE_BY_DATE_Result> SIMPLE_SEARCH_RFC_69B_DAYDATE_BY_DATE(string rFC, Nullable<int> tIPO, string fECHA)
        {
            var rFCParameter = rFC != null ?
                new ObjectParameter("RFC", rFC) :
                new ObjectParameter("RFC", typeof(string));
    
            var tIPOParameter = tIPO.HasValue ?
                new ObjectParameter("TIPO", tIPO) :
                new ObjectParameter("TIPO", typeof(int));
    
            var fECHAParameter = fECHA != null ?
                new ObjectParameter("FECHA", fECHA) :
                new ObjectParameter("FECHA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SIMPLE_SEARCH_RFC_69B_DAYDATE_BY_DATE_Result>("SIMPLE_SEARCH_RFC_69B_DAYDATE_BY_DATE", rFCParameter, tIPOParameter, fECHAParameter);
        }
    }
}
