//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SATSR
{
    using System;
    using System.Collections.Generic;
    
    public partial class UPDATE
    {
        public int ID { get; set; }
        public int ID_SOURCE_TYPE { get; set; }
        public string NAME { get; set; }
        public System.DateTime DATE_UPDATE { get; set; }
        public int RECORDS { get; set; }
        public int M { get; set; }
        public int F { get; set; }
        public string TABLE_QUERY { get; set; }
        public bool EXEC_TRIGGER { get; set; }
        public bool EXEC_ALERT { get; set; }
    
        public virtual SOURCE_TYPE SOURCE_TYPE { get; set; }
    }
}
