//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SATSR
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_SEARCH_HISTORY
    {
        public int ID { get; set; }
        public int ID_USER { get; set; }
        public System.DateTime INSERT_DATE { get; set; }
        public string RFC { get; set; }
        public string NAME { get; set; }
        public string C69 { get; set; }
        public string C69_B { get; set; }
        public Nullable<int> TYPE_SEARCH { get; set; }
        public Nullable<System.DateTime> SEARCH_DATE { get; set; }
        public Nullable<int> C69_C { get; set; }
        public Nullable<int> C69_BC { get; set; }
        public Nullable<System.DateTime> C69_B_DATE { get; set; }
    
        public virtual USER USER { get; set; }
    }
}
